#!/bin/bash

############################################################################
#####	File		: ngit						####
####	Description	: The intent is to enhance git capabilities	####
#####	Author		: Melike Eroglu <meroglu@netas.com.tr>		####
#####	Co-Author	: Can Okcelik   <cokcelik@netas.com.tr>		####
#####	Creation Date	: 31/07/2015					####
############################################################################

if [ "$1" = "pushall" ];
then
#	git remote add asd ssh://git@zistvy90:7999/~cokcelik/melike.git 
#	git remote add bsd ssh://git@zistvy90:7999/~cokcelik/melike.git
        git config --global push.default matching
	netas_commit_id=$( git log | head -1 | sed s/'commit '// ) 
	git push netas  $2
	
	if [[ $? -ne 0 ]]; then
		echo "==> Netas is not available <==";
	
		if [[ $? -ne 0 ]]
        	then
        		echo "We can not revert the last commit has been sent Netas site recently. Now, two sites are not sync."
        	else
                	echo "Last commit has been reverted from Netas site."
        	fi

		exit;	
	else

		echo "----- Commit has been pushed to Netas site. -----"
	fi

         git push genband $2
        if [[ $? -ne 0 ]]; then
                echo "==> Genband is not available <==";
		git revert --no-edit $netas_commit_id		
		if [[ $? -ne 0 ]]
		then
			echo "We can not revert the last commit has been sent Netas site recently. Now, two sites are not sync."
		else
			echo "Last commit has been reverted from Netas site."
		fi
        else
              echo "----- Commit has been pushed to Genband site. -----"
        fi


else
	echo "This file is used for multi-site push operation. Please do not use this file out of its bounds."
fi
